version: '3.8'

services:
  # NetApp StorageGRID Simulator using MinIO with NetApp-like configuration
  netapp-s3:
    image: minio/minio:latest
    container_name: netapp-s3-simulator
    restart: unless-stopped
    ports:
      - "9010:9000"  # S3 API port (avoiding conflict with existing MinIO)
      - "9011:9001"  # Console port
    environment:
      MINIO_ROOT_USER: netapp-admin
      MINIO_ROOT_PASSWORD: netapp-secure-password-2024
      MINIO_DOMAIN: netapp-storagegrid.local
      MINIO_SERVER_URL: http://localhost:9010
      # NetApp StorageGRID specific configurations
      MINIO_REGION_NAME: us-east-1
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9011
    command: server /data --console-address ":9001"
    volumes:
      - netapp_s3_data:/data
    networks:
      - netapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # NetApp Trident CSI Plugin Simulator (for Kubernetes integration testing)
  trident-simulator:
    image: alpine:latest
    container_name: trident-simulator
    restart: unless-stopped
    command: >
      sh -c "
        echo 'NetApp Trident CSI Plugin Simulator'
        echo 'Simulating StorageGRID S3 backend connectivity...'
        echo 'S3 Endpoint: http://netapp-s3:9000'
        echo 'Access Key: netapp-admin'
        echo 'Secret Key: netapp-secure-password-2024'
        echo 'Default Bucket: trident-storage'
        echo 'Status: Ready for S3 operations'
        tail -f /dev/null
      "
    depends_on:
      - netapp-s3
    networks:
      - netapp-network
    environment:
      NETAPP_S3_ENDPOINT: http://netapp-s3:9000
      NETAPP_ACCESS_KEY: netapp-admin
      NETAPP_SECRET_KEY: netapp-secure-password-2024
      NETAPP_DEFAULT_BUCKET: trident-storage
      NETAPP_REGION: us-east-1

volumes:
  netapp_s3_data:
    driver: local

networks:
  netapp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16