version: '3.8'

services:
  db2:
    image: ibmcom/db2:11.5.7.0a
    container_name: bfb-awss3light-db2
    restart: unless-stopped
    privileged: true
    ports:
      - "50000:50000"
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password123
      DBNAME: BFBTEMPL
      BLU: false
      ENABLE_ORACLE_COMPATIBILITY: false
      UPDATEAVAIL: NO
      TO_CREATE_SAMPLEDB: false
      REPODB: false
    volumes:
      - db2_data:/database
    networks:
      - bfb-awss3light-network
    healthcheck:
      test: ["CMD", "su", "-", "db2inst1", "-c", "db2 connect to BFBTEMPL"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s

volumes:
  db2_data:

networks:
  bfb-awss3light-network:
    driver: bridge
